d-my_project
d--settings
f---__init__.py
f---dev.py
f---prod.py
d--mainapp
f---__init__.py
f---models.py
f---views.py
d---templates
d----mainapp
f-----base.html
f-----index.html
d--authapp
f---__init__.py
f---models.py
f---views.py
d---templates
f----authapp
f----base.html
f----index.html